#!/usr/bin/env bash
# This script installs Nginx web server and configures it to meet the requirements
#!/usr/bin/env bash
# Install NGINX
apt update
apt install -y nginx
echo "Hello World!" > /var/www/html/index.html
service nginx restart
